### PR TITLE
debug add icon

### PR DESCRIPTION
**Pull request by d1y**
This PR uses [VScode codicons](https://github.com/microsoft/vscode-codicons) as icons

image

Release Notes:

- N/A

### CODE REVIEW

**Comment by RemcoSmitsDev** [comment]
Thanks! Is it ready to be merged?

**Comment by d1y** [comment]
> Thanks! Is it ready to be merged?

I would like to know if I need to add license instructions for VScode-codicon?

**Comment by d1y** [comment]
I don't think we need to worry about it
image

If it were me, it might explain :)
image

Let's merge it

**Comment by RemcoSmitsDev** [comment]
Oke, yeah I think they also want to make their own icons so they are more inline with zed icons that are already in Zed. But for now I thinks its fine.

**Pull request merged**
